services:
  db:
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - ./database/postgres-init:/docker-entrypoint-initdb.d:Z
    healthcheck:
      interval: 10s
      retries: 10
      test: 'pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"'
      timeout: 2s
  app-admin:
    image: nocodb/nocodb:latest
    env_file: .env
    ports:
      - 4444:3333
    depends_on:
      db:
        condition: service_healthy
